# Generated by Django 3.2.5 on 2021-08-12 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='save',
            field=models.BooleanField(default=False),
        ),
    ]
