# Generated by Django 3.2.5 on 2021-08-13 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_post_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='save',
            new_name='save_post',
        ),
    ]
