# Generated by Django 3.2.5 on 2021-08-13 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0012_rename_save_post_save_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='save_post',
        ),
        migrations.AddField(
            model_name='post',
            name='save_post',
            field=models.ManyToManyField(blank=True, related_name='save_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
